{
 "title": "Cloudbuild",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "graph",
   "description": "Uptime of dispatch cloud build service (in seconds)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_uptime{job=\"dispatch-event-sink\"}",
     "legendFormat": "{{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"dispatch-event-sink\", namespace=\"dispatch\"}[1m])",
     "legendFormat": "{{namespace}}/{{job}}/process_cpu_seconds_total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "go_memstats_alloc_bytes – a metric which shows how much bytes of memory is allocated on the Heap for the Objects. The value is same as go_memstats_heap_alloc_bytes. This metric counts all reachable heap objects plus unreachable objects, GC has not yet freed.\n\n\ngo_memstats_alloc_bytes_total – this metric increases as objects are allocated in the Heap, but doesn’t decrease when they are freed. I think it is immensly useful, as it is only increasing number and has same nice properties that Prometheus Counter has. Doing rate() on it should show us how many bytes/s of memory app consumes and is “durable” across restarts and scrape misses.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(go_memstats_alloc_bytes{namespace=\"dispatch\", job=\"dispatch-event-sink\"})/(1024)",
     "legendFormat": "{{job}}/go_memstats_alloc_kilobytes"
    }
   ]
  },
  {
   "title": "processed_events per status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "processed_events{job=\"dispatch-event-sink\"}",
     "legendFormat": "{{namespace}}/processed_events/{{status}}"
    }
   ]
  },
  {
   "title": "outstanding_events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_events{job=\"dispatch-event-sink\"}",
     "legendFormat": "{{namespace}}/outstanding_events"
    }
   ]
  },
  {
   "title": "active_pipelines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "active_pipelines{job=\"dispatch-event-sink\"}",
     "legendFormat": "{{namespace}}/active_pipelines/{{status}}"
    }
   ]
  },
  {
   "title": "completed_pipelines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "completed_pipelines{job=\"dispatch-event-sink\"}",
     "legendFormat": "{{namespace}}/completed_pipelines/{{status}}"
    }
   ]
  },
  {
   "title": "active_tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "active_tasks{job=\"dispatch-event-sink\"}",
     "legendFormat": "{{namespace}}/active_tasks/{{status}}"
    }
   ]
  },
  {
   "title": "completed_tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "completed_tasks{job=\"dispatch-event-sink\"}",
     "legendFormat": "{{namespace}}/completed_tasks/{{status}}"
    }
   ]
  },
  {
   "title": "event_processing_time rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(event_processing_time_sum{job=\"dispatch-event-sink\"}[5m]) / rate(event_processing_time_count{job=\"dispatch-event-sink\"}[5m]))",
     "legendFormat": "{{namespace}}/event_processing_time"
    }
   ]
  },
  {
   "title": "pipeline_completion_time rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(pipeline_completion_time_sum{job=\"dispatch-event-sink\"}[5m]) / rate(pipeline_completion_time_count{job=\"dispatch-event-sink\"}[5m]))",
     "legendFormat": "{{namespace}}/pipeline_completion_time"
    }
   ]
  },
  {
   "title": "event_processing_time_bucket - 90 Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(event_processing_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "pipeline_completion_time_bucket completion time - 90 Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(pipeline_completion_time_bucket[10m])) by (le))"
    }
   ]
  },
  {
   "title": "event_processing_time_bucket apdex score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(event_processing_time_bucket{le=\"10\"}[5m])) by (job)\n+\n  sum(rate(event_processing_time_bucket{le=\"+Inf\"}[5m])) by (job)\n) / 2 / sum(rate(event_processing_time_bucket[5m])) by (job)",
     "legendFormat": "{{namespace}}/event_processing_time_apdex"
    }
   ]
  },
  {
   "title": "pipeline_completion_time_bucket apdex score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(pipeline_completion_time_bucket{le=\"10\"}[5m])) by (job)\n+\n  sum(rate(pipeline_completion_time_bucket{le=\"+Inf\"}[5m])) by (job)\n) / 2 / sum(rate(pipeline_completion_time_count[5m])) by (job)",
     "legendFormat": "{{namespace}}/pipeline_completion_time_bucket"
    }
   ]
  }
 ]
}